# sid_data.py

SID_ENTRIES = [
    {"sid": "S-1-16-28672", "name": "Secure Process Mandatory Level",
     "description": "Уровень целостности процесса: безопасный (Secure Process). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-20480", "name": "Protected Process Mandatory Level",
     "description": "Уровень целостности процесса: защищённый (Protected Process). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-16384", "name": "System Mandatory Level",
     "description": "Системный уровень целостности (System). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-12288", "name": "High Mandatory Level",
     "description": "Высокий уровень целостности (High). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-8448", "name": "Medium Plus Mandatory Level",
     "description": "Средне-повышенный уровень целостности (Medium Plus). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-8192", "name": "Medium Mandatory Level",
     "description": "Средний уровень целостности (Medium). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-4096", "name": "Low Mandatory Level",
     "description": "Низкий уровень целостности (Low). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-16-0", "name": "Untrusted Mandatory Level",
     "description": "Недоверенный уровень целостности (Untrusted). Добавлен в Windows Vista и Windows Server 2008.", "fsmo_role": ""},

    {"sid": "S-1-5", "name": "NT Authority",
     "description": "Авторитет идентификатора (NT Authority).", "fsmo_role": ""},

    {"sid": "S-1-5-21domain-572", "name": "Denied RODC Password Replication Group",
     "description": "Группа Domain Local. Члены не могут реплицировать пароли на read-only контроллеры домена.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-21domain-498", "name": "Enterprise Read-only Domain Controllers",
     "description": "Универсальная группа. Члены — read-only контроллеры домена во всей организации.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-21domain-521", "name": "Read-only Domain Controllers",
     "description": "Глобальная группа. Члены — read-only контроллеры в этом домене.", "fsmo_role": "PDC Emulator"},

    {"sid": "S-1-5-83-0", "name": r"NT VIRTUAL MACHINE\Virtual Machines",
     "description": "Встроенная группа для Hyper‑V. Создаётся при установке роли, управляется службой VMMS. Требует прав Create Symbolic Links и Log on as a Service. Добавлено в Windows 8 и Windows Server 2012.", "fsmo_role": ""},

    {"sid": "S-1-5-80", "name": "NT Service",
     "description": "Префикс для учётных записей служб (NT Service).", "fsmo_role": ""},
    {"sid": "S-1-5-80-0", "name": "All Services",
     "description": "Группа всех процессов служб, контролируется ОС. Добавлено в Windows Vista и Windows Server 2008.", "fsmo_role": ""},
    {"sid": "S-1-5-80-0", "name": r"NT SERVICES\ALL SERVICES",
     "description": "Группа всех процессов служб, контролируется ОС. Добавлено в Windows Server 2008 R2.", "fsmo_role": ""},

    {"sid": "S-1-5-64-21", "name": "Digest Authentication",
     "description": "SID, используемый пакетом Digest для аутентификации клиента.", "fsmo_role": ""},
    {"sid": "S-1-5-64-14", "name": "SChannel Authentication",
     "description": "SID, используемый пакетом SChannel для аутентификации клиента.", "fsmo_role": ""},
    {"sid": "S-1-5-64-10", "name": "NTLM Authentication",
     "description": "SID, используемый пакетом NTLM для аутентификации клиента.", "fsmo_role": ""},

    {"sid": "S-1-5-32-580", "name": r"BUILTIN\Remote Management Users",
     "description": "Builtin локальная группа. Доступ к WMI через WinRM.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-579", "name": r"BUILTIN\Access Control Assistance Operators",
     "description": "Builtin локальная группа. Удалённый запрос атрибутов и прав авторизации.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-578", "name": r"BUILTIN\Hyper-V Administrators",
     "description": "Builtin локальная группа. Полный доступ к Hyper‑V.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-577", "name": r"BUILTIN\RDS Management Servers",
     "description": "Builtin локальная группа для управления RDS-серверами. Требуется для серверов RD Connection Broker и RD Session Host.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-576", "name": r"BUILTIN\RDS Endpoint Servers",
     "description": "Builtin локальная группа для серверов RemoteApp и личных ВМ. Требуется на RD Connection Broker, RD Session Host, RD Virtualization Host.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-575", "name": r"BUILTIN\RDS Remote Access Servers",
     "description": "Builtin локальная группа для доступа к ресурсам RemoteApp. Требуется на RD Gateway и RD Web Access.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-574", "name": r"BUILTIN\Certificate Service DCOM Access",
     "description": "Builtin локальная группа. Доступ к Certification Authorities в домене.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-573", "name": r"BUILTIN\Event Log Readers",
     "description": "Builtin локальная группа. Чтение локальных журналов событий.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-569", "name": r"BUILTIN\Cryptographic Operators",
     "description": "Builtin локальная группа. Выполнение криптографических операций.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-562", "name": r"BUILTIN\Distributed COM Users",
     "description": "Алиас. Контроль доступа COM-вызовов на компьютере.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-561", "name": r"BUILTIN\Terminal Server License Servers",
     "description": "Алиас. Группа для лицензирования терминального сервера (SP1 Windows Server 2003).", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-560", "name": r"BUILTIN\Windows Authorization Access group",
     "description": "Алиас. Доступ к атрибуту tokengroupsGlobalAndUniversal.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-559", "name": r"BUILTIN\Performance Log Users",
     "description": "Алиас. Удалённое планирование логирования производительности.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-558", "name": r"BUILTIN\Performance Monitor Users",
     "description": "Алиас. Удалённое мониторирование системы.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-557", "name": r"BUILTIN\Incoming Forest Trust Builders",
     "description": "Алиас. Создание входящих доверительных отношений.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-556", "name": r"BUILTIN\Network Configuration Operators",
     "description": "Алиас. Управление сетевыми настройками.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-555", "name": r"BUILTIN\Remote Desktop Users",
     "description": "Алиас. Право на удалённый вход в систему.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-32-554", "name": r"BUILTIN\Pre‑Windows 2000 Compatible Access",
     "description": "Алиас. Обратная совместимость: чтение всех пользователей/групп.", "fsmo_role": "PDC Emulator"},

    {"sid": "S-1-5-32-552", "name": "Replicators",
     "description": "Builtin local group для File Replication Service на DC. По умолчанию пуста.", "fsmo_role": ""},
    {"sid": "S-1-5-32-551", "name": "Backup Operators",
     "description": "Builtin local group. Бэкап, восстановление, выключение системы.", "fsmo_role": ""},
    {"sid": "S-1-5-32-550", "name": "Print Operators",
     "description": "Builtin group на DC. Управление принтерами и очередями.", "fsmo_role": ""},
    {"sid": "S-1-5-32-549", "name": "Server Operators",
     "description": "Builtin group на DC. Управление сервисами, шарами, бэкапы, форматирование и выключение.", "fsmo_role": ""},
    {"sid": "S-1-5-32-548", "name": "Account Operators",
     "description": "Builtin group на DC. Создание и модификация учётных записей (кроме Builtin и DC OU).", "fsmo_role": ""},
    {"sid": "S-1-5-32-547", "name": "Power Users",
     "description": "Builtin group. Управление локальными пользователями/группами, установка ПО.", "fsmo_role": ""},
    {"sid": "S-1-5-32-546", "name": "Guests",
     "description": "Builtin group. Только аккаунт Guest по умолчанию. Ограниченные права.", "fsmo_role": ""},
    {"sid": "S-1-5-32-545", "name": "Users",
     "description": "Builtin group. Authenticated Users по умолчанию, при домене добавляется Domain Users.", "fsmo_role": ""},
    {"sid": "S-1-5-32-544", "name": "Administrators",
     "description": "Builtin group. Administrator по умолчанию, при присоединении к домену — Domain Admins, на DC — Enterprise Admins.", "fsmo_role": ""},

    {"sid": "S-1-5-21domain-571", "name": "Allowed RODC Password Replication Group",
     "description": "Domain Local group. Репликация паролей на все read-only контроллеры.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-21domain-522", "name": "Cloneable Domain Controllers",
     "description": "Global group. Члены — контроллеры домена, доступные для клонирования.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-21domain-500", "name": "Administrator",
     "description": "Учётная запись администратора системы.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-501", "name": "Guest",
     "description": "Гостевая учётная запись без пароля (по умолчанию отключена).", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-502", "name": "KRBTGT",
     "description": "Учётная запись Kerberos Ticket Granting Ticket (KDC).", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-512", "name": "Domain Admins",
     "description": "Global группа администраторов домена.", "fsmo_role": "PDC Emulator"},
    {"sid": "S-1-5-21domain-513", "name": "Domain Users",
     "description": "Global группа всех пользователей домена.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-514", "name": "Domain Guests",
     "description": "Global группа гостей домена.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-515", "name": "Domain Computers",
     "description": "Global группа компьютеров домена.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-516", "name": "Domain Controllers",
     "description": "Global группа контроллеров домена.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-517", "name": "Cert Publishers",
     "description": "Global группа CA-компьютеров, публикация сертификатов.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-520", "name": "Group Policy Creator Owners",
     "description": "Global группа, создаёт объекты групповой политики.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-526", "name": "Key Admins",
     "description": "Security группа, делегированный доступ к атрибуту msdsKeyCredentialLink.", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-527", "name": "Enterprise Key Admins",
     "description": "Security группа для доверенных внешних властей (AD FS).", "fsmo_role": ""},
    {"sid": "S-1-5-21domain-553", "name": "RAS and IAS Servers",
     "description": "Domain Local group. Доступ к атрибутам и информации входа для RAS/IAS.", "fsmo_role": ""},

    {"sid": "S-1-5-21root domain-518", "name": "Schema Admins",
     "description": "Universal группа (native-mode) или Global группа (mixed-mode). Управление схемой AD. По умолчанию — Administrator лесового корневого домена.", "fsmo_role": ""},
    {"sid": "S-1-5-21root domain-519", "name": "Enterprise Admins",
     "description": "Universal группа (native-mode) или Global группа (mixed-mode). Управление лесом AD. По умолчанию — Administrator лесового корневого домена.", "fsmo_role": ""},

    {"sid": "S-1-5-20", "name": "Network Service",
     "description": "NT Authority; учётная запись сетевой службы с сетевым доступом.", "fsmo_role": ""},
    {"sid": "S-1-5-19", "name": "Local Service",
     "description": "NT Authority; учётная запись локальной службы без сетевого доступа.", "fsmo_role": ""},
    {"sid": "S-1-5-17", "name": "This Organization",
     "description": "Учётная запись по умолчанию для IIS.", "fsmo_role": ""},
    {"sid": "S-1-5-15", "name": "This Organization",
     "description": "Группа всех пользователей одной организации (AD).", "fsmo_role": ""},
    {"sid": "S-1-5-14", "name": "Remote Interactive Logon",
     "description": "Группа пользователей, подключившихся через терминальные службы.", "fsmo_role": ""},
    {"sid": "S-1-5-13", "name": "Terminal Server Users",
     "description": "Группа пользователей терминального сервера.", "fsmo_role": ""},
    {"sid": "S-1-5-12", "name": "Restricted Code",
     "description": "SID зарезервирован для будущего использования.", "fsmo_role": ""},
    {"sid": "S-1-5-11", "name": "Authenticated Users",
     "description": "Группа всех аутентифицированных пользователей.", "fsmo_role": ""},
    {"sid": "S-1-5-10", "name": "Principal Self",
     "description": "Плейсхолдер в ACE, заменяется на SID текущего субъекта.", "fsmo_role": ""},
    {"sid": "S-1-5-9", "name": "Enterprise Domain Controllers",
     "description": "Группа всех контроллеров домена в лесу.", "fsmo_role": ""},
    {"sid": "S-1-5-8", "name": "Proxy",
     "description": "Не используется в Windows 2000.", "fsmo_role": ""},
    {"sid": "S-1-5-7", "name": "Anonymous",
     "description": "Группа анонимных пользователей.", "fsmo_role": ""},
    {"sid": "S-1-5-6", "name": "Service",
     "description": "Группа всех служб, выполнивших вход как сервис.", "fsmo_role": ""},
    {"sid": "S-1-5-5-X-Y", "name": "Logon Session",
     "description": "Сессия входа. X и Y уникальны для каждой сессии.", "fsmo_role": ""},
    {"sid": "S-1-5-4", "name": "Interactive",
     "description": "Группа пользователей, выполнивших вход интерактивно.", "fsmo_role": ""},
    {"sid": "S-1-5-3", "name": "Batch",
     "description": "Группа пользователей, выполнивших вход пакетно.", "fsmo_role": ""},
    {"sid": "S-1-5-2", "name": "Network",
     "description": "Группа пользователей, выполнивших вход по сети.", "fsmo_role": ""},
    {"sid": "S-1-5-1", "name": "Dialup",
     "description": "Группа пользователей, выполнивших вход через dial-up.", "fsmo_role": ""},
    {"sid": "S-1-4", "name": "Non-unique Authority",
     "description": "Идентификатор авторитета (Non-unique).", "fsmo_role": ""},
    {"sid": "S-1-3", "name": "Creator Authority",
     "description": "Идентификатор авторитета (Creator).", "fsmo_role": ""},
    {"sid": "S-1-3-4", "name": "Owner Rights",
     "description": "Группа прав владельца. ACE игнорирует READ_CONTROL и WRITE_DAC для владельца.", "fsmo_role": ""},
    {"sid": "S-1-3-3", "name": "Creator Group Server",
     "description": "Не используется в Windows Server 2000.", "fsmo_role": ""},
    {"sid": "S-1-3-2", "name": "Creator Owner Server",
     "description": "Не используется в Windows Server 2000.", "fsmo_role": ""},
    {"sid": "S-1-3-1", "name": "Creator Group",
     "description": "Плейсхолдер в ACE, заменяется на первичную группу создателя.", "fsmo_role": ""},
    {"sid": "S-1-3-0", "name": "Creator Owner",
     "description": "Плейсхолдер в ACE, заменяется на SID создателя объекта.", "fsmo_role": ""},
    {"sid": "S-1-2", "name": "Local Authority",
     "description": "Идентификатор авторитета (Local).", "fsmo_role": ""},
    {"sid": "S-1-2-1", "name": "Console Logon",
     "description": "Группа пользователей, вошедших на физическую консоль. Добавлено в Windows 7 и Server 2008 R2.", "fsmo_role": ""},
    {"sid": "S-1-2-0", "name": "Local",
     "description": "Группа пользователей, вошедших локально.", "fsmo_role": ""},
    {"sid": "S-1-1", "name": "World Authority",
     "description": "Идентификатор авторитета (World).", "fsmo_role": ""},
    {"sid": "S-1-1-0", "name": "Everyone",
     "description": "Все пользователи, включая анонимных и гостей. По умолчанию не включает анонимных на XP SP2+", "fsmo_role": ""},
    {"sid": "S-1-0", "name": "Null Authority",
     "description": "Идентификатор авторитета (NULL).", "fsmo_role": ""},
    {"sid": "S-1-0-0", "name": "Nobody",
     "description": "Нет субъекта безопасности.", "fsmo_role": ""},
]
